version: '3'

networks:
  gamenet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.24.0.0/16
          gateway: 172.24.0.1

services:
  redis:
    image: redis:7.2.4
    container_name: gameredis
    restart: always
    environment:
      - TZ
    command: redis-server /etc/redis.conf 
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 20s
      retries: 5  
    ports:
      - 6379:6379
    volumes:
      - ./database/redis_data:/data:rw
      - ./conf/redis.conf:/etc/redis.conf:ro
    networks:
      gamenet:
        ipv4_address: 172.24.0.102
  mysql:
    image: mysql:8.0
    container_name: gamemysql
    restart: always
    ports:
      - 3306:3306
    command: --lower_case_table_names=1
    environment:
      - TZ
      - MYSQL_ROOT_PASSWORD
#      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./database/mysql_data:/var/lib/mysql:rw
      - ./logs/mysql:/var/log/mysql:rw
      - ./conf/mysql:/etc/mysql/mysql.conf.d
      - ./conf/mysql/my.cnf:/etc/my.cnf 
        #    healthcheck:
#      test: ["CMD", "mysql", "--user=$MYSQL_USER","--password=$MYSQL_PASSWORD","-e","SHOW DATABASES;"]
#      timeout: 5s
#      retries: 5
    networks:
      gamenet:
        ipv4_address: 172.24.0.103
  php-fpm:
    restart: always
    container_name: gamephp
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - ADMIN_HOST
      - APPID_BETCAT_PAYMENT
      - APPID_BETCAT_PAYOUT
      - SECRET_BETCAT_PAYOUT
      - SECRET_BETCAT_PAYMENT
      - BETCAT_HOST
      - NOTIFY_BETCAT_PAYMENT
      - NOTIFY_BETCAT_PAYOUT
      - AWS_S3_KEY
      - AWS_S3_SECRET
      - INPAY_PAYOUT_HOST
      - INPAY_PAYOUT_APP_TOKEN
      - INPAY_PAYOUT_ENVIRONMENT
      - INPAY_PAYOUT_NOTIFY_URL
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - ./backstage:/app:rw
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      gamenet:
        ipv4_address: 172.24.0.101
  web:
    restart: always
    container_name: gamenginx
    build:
      context: ./
      dockerfile: ./docker/nginx/Dockerfile
    depends_on:
      - php-fpm
    ports:
      - 18080:80
      - 2348:2348
      - 2000:2000
      - 1236:1236
      - 2020:2020
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - ADMIN_HOST
      - APPID_BETCAT_PAYMENT
      - APPID_BETCAT_PAYOUT
      - SECRET_BETCAT_PAYOUT
      - SECRET_BETCAT_PAYMENT
      - BETCAT_HOST
      - NOTIFY_BETCAT_PAYMENT
      - NOTIFY_BETCAT_PAYOUT
      - AWS_S3_KEY
      - AWS_S3_SECRET
      - INPAY_PAYOUT_HOST
      - INPAY_PAYOUT_APP_TOKEN
      - INPAY_PAYOUT_ENVIRONMENT
      - INPAY_PAYOUT_NOTIFY_URL
    networks:
      gamenet:
        ipv4_address: 172.24.0.100
    volumes:
      - ./backstage:/app:rw
      - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./logs/nginx:/var/log/nginx
      - ./docker/nginx/html:/usr/share/nginx/html
  game-server:
     restart: always 
     container_name: gameservice
     build: 
       context: ./
       dockerfile: ./docker/game/server/Dockerfile
     environment:
       - TZ
       - MYSQL_HOST
       - MYSQL_USER
       - MYSQL_PASSWORD
       - MYSQL_PORT
       - REDIS_HOST
       - REDIS_PASSWORD
       - REDIS_PORT 
       - ADMIN_HOST
       - HALL_URL 
       - BROADCAST_IP 
     depends_on:
       - mysql
     ports:
       - 13000:13000
     networks:
       gamenet:
         ipv4_address: 172.24.0.104
     volumes:
       - ./slots_server/server:/app/server
       - ./slots_server/node_modules:/app/node_modules
       - ./slots_server/util:/app/util 
       - ./slots_server/CClass:/app/CClass
       - ./logs/game/server:/app/server/logs
  game-broadcast:
    restart: always 
    container_name: gameBroadcastserver
    build: 
      context: ./
      dockerfile: ./docker/game/Broadcast_server/Dockerfile
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 13001:13001
    depends_on:
      - mysql
    networks:
      gamenet:
        ipv4_address: 172.24.0.105
    volumes:
      - ./slots_server/broadcast_server:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/Broadcast_server:/app/server/logs
  game-laba129freespin:
    restart: always 
    container_name: gamelaba129freespin
    build: 
      context: ./
      dockerfile: ./docker/game/laba_129_freespin/Dockerfile
    depends_on:
      - mysql
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15129:15129
    networks:
      gamenet:
        ipv4_address: 172.24.0.106
    volumes:
      - ./slots_server/laba_129_freespin:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba129freespin:/app/server/logs
  game-laba163ganeshagold:
    restart: always 
    container_name: gamelaba163ganeshagold
    build: 
      context: ./
      dockerfile: ./docker/game/laba_163_ganeshagold/Dockerfile
    depends_on:
      - mysql
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15163:15163
    networks:
      gamenet:
        ipv4_address: 172.24.0.107
    volumes:
      - ./slots_server/laba_163_ganeshagold:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba163ganeshagold:/app/server/logs
  game-laba168fortunetiger:
    restart: always 
    container_name: gamelaba168fortunetiger
    build: 
      context: ./
      dockerfile: ./docker/game/laba_168_fortunetiger/Dockerfile
    depends_on:
      - mysql
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15168:15168
    networks:
      gamenet:
        ipv4_address: 172.24.0.108
    volumes:
      - ./slots_server/laba_168_fortunetiger:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba168fortunetiger:/app/server/logs      
  game-laba172jungledelight:
    restart: always 
    container_name: gamelaba172jungledelight
    build: 
      context: ./
      dockerfile: ./docker/game/laba_172_jungledelight/Dockerfile
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    depends_on:
      - mysql
    ports:
      - 15172:15172
    networks:
      gamenet:
        ipv4_address: 172.24.0.109
    volumes:
      - ./slots_server/laba_172_jungledelight:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba172jungledelight:/app/server/logs
  game-laba183ultimatestriker:
    restart: always 
    container_name: gamelaba183ultimatestriker
    build: 
      context: ./
      dockerfile: ./docker/game/laba_183_UltimateStriker/Dockerfile
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15183:15183
    depends_on:
      - mysql
    networks:
      gamenet:
        ipv4_address: 172.24.0.110
    volumes:
      - ./slots_server/laba_183_UltimateStriker:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba183ultimatestriker:/app/server/logs
  game-laba185buffaloking:
    restart: always 
    container_name: gamelaba185buffaloking
    build: 
      context: ./
      dockerfile: ./docker/game/laba_185_BuffaloKing/Dockerfile
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15185:15185
    depends_on:
      - mysql
    networks:
      gamenet:
        ipv4_address: 172.24.0.111
    volumes:
      - ./slots_server/laba_185_BuffaloKing:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba185buffaloking:/app/server/logs
  game-laba186digdigdigger:
    restart: always 
    container_name: gamelaba186DigDigDigger
    build: 
      context: ./
      dockerfile: ./docker/game/laba_186_DigDigDigger/Dockerfile
    depends_on:
      - mysql
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15186:15186
    networks:
      gamenet:
        ipv4_address: 172.24.0.112
    volumes:
      - ./slots_server/laba_186_DigDigDigger:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba186DigDigDigger:/app/server/logs
  game-laba187grandwheel:
    restart: always 
    container_name: gamelaba187GrandWheel
    build: 
      context: ./
      dockerfile: ./docker/game/laba_187_GrandWheel/Dockerfile
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    ports:
      - 15187:15187
    depends_on:
      - mysql
    networks:
      gamenet:
        ipv4_address: 172.24.0.113
    volumes:
      - ./slots_server/laba_187_GrandWheel:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba187GrandWheel:/app/server/logs
  game-laba188grandwheel:
    restart: always 
    container_name: gamelaba188BlueDiamond
    build: 
      context: ./
      dockerfile: ./docker/game/laba_188_BlueDiamond/Dockerfile
    ports:
      - 15188:15188
    depends_on:
      - mysql
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_USER=root
      - MYSQL_PASSWORD
      - MYSQL_PORT
      - REDIS_HOST
      - REDIS_PASSWORD
      - REDIS_PORT 
      - HALL_URL 
      - BROADCAST_IP 
    networks:
      gamenet:
        ipv4_address: 172.24.0.114
    volumes:
      - ./slots_server/laba_188_BlueDiamond:/app/server
      - ./slots_server/node_modules:/app/node_modules
      - ./slots_server/util:/app/util 
      - ./slots_server/CClass:/app/CClass
      - ./logs/game/laba188BlueDiamond:/app/server/logs
 
           
          
          
          
 
